import './style.css';

type Take = { id: string; name: string; blob: Blob; waveform: number[]; loudness: number; noise: number; duration: number; created: number };
type Route = '/' | '/demo' | '/privacy' | '/terms' | '/404';
const app = document.querySelector<HTMLDivElement>('#app')!;
const STORE = 'voice-comfort-meter';
const demo = () => location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let takes: Take[] = [];
let stream: MediaStream | null = null;
let recorder: MediaRecorder | null = null;
let analyser: AnalyserNode | null = null;
let audioCtx: AudioContext | null = null;
let recordingTimer = 0;
let savedScroll = new Map<string, number>();

function db() { return new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open(STORE, 1); r.onupgradeneeded = () => r.result.createObjectStore('takes'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
const key = () => demo() ? 'demo:takes' : 'real:takes';
async function load() { const d = await db(); takes = await new Promise<Take[]>((resolve, reject) => { const r = d.transaction('takes').objectStore('takes').get(key()); r.onsuccess = () => resolve(r.result || []); r.onerror = () => reject(r.error); }); d.close(); }
async function save() { const d = await db(); await new Promise<void>((resolve, reject) => { const r = d.transaction('takes', 'readwrite').objectStore('takes').put(takes, key()); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); d.close(); }
async function clear() { takes = []; await save(); render(); }
function esc(s: string) { return s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)); }
function title(route: Route) { return route === '/privacy' ? 'Privacy — Voice Comfort Meter' : route === '/terms' ? 'Terms — Voice Comfort Meter' : route === '/demo' ? 'Demo — Voice Comfort Meter' : route === '/404' ? 'Not found — Voice Comfort Meter' : 'Voice Comfort Meter — Compare private voice takes'; }
function route(): Route { const p = location.pathname.replace(/\/$/, '') || '/'; return (['/','/demo','/privacy','/terms','/404'] as string[]).includes(p) ? p as Route : '/404'; }
function navigate(path: string) { savedScroll.set(location.pathname, scrollY); history.pushState({}, '', path); render(); }
function layout(content: string, h1: string) { return `<a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="/" data-link><span>◉</span> Voice Comfort Meter</a><nav aria-label="Main navigation"><a href="/demo" data-link>Demo</a><a href="#how" data-link>How it works</a><a href="/privacy" data-link>Privacy</a></nav></header><div class="route-note" aria-live="polite"></div><main id="main" tabindex="-1">${content}</main><footer><span>Private feedback for your next take.</span><span><a href="/privacy" data-link>Privacy</a> · <a href="/terms" data-link>Terms</a></span><span>Built by Param Factory · v1.0.0</span></footer>`; }
function demoBanner() { return demo() ? `<aside class="demo-banner" aria-label="Demo mode"><b>Demo — sample data, nothing is saved</b><span><button class="text-btn" data-reset-demo>Reset demo</button><button class="text-btn" data-real>Start for real</button></span></aside>` : ''; }
function facts() { return `<ul class="facts"><li><b>Private</b><span>Audio stays on this device.</span></li><li><b>Offline ready</b><span>Use it after the first visit.</span></li><li><b>Free</b><span>No account or payment.</span></li></ul>`; }
function landing() { return layout(`${demoBanner()}<section class="hero"><div class="hero-copy"><p class="eyebrow">A small recording check</p><h1>Compare two voice takes privately</h1><p class="lede">For speakers and singers who want calmer, clearer recording choices.</p><div class="hero-actions"><button class="primary" data-demo>Try it with sample data</button><span>See two example takes right away.</span></div>${facts()}</div><figure><img src="/art/blueprint-hero.webp" width="1200" height="800" fetchpriority="high" alt="A microphone and headphones drawn on a blue recording blueprint." /><figcaption>Original illustration generated for Voice Comfort Meter.</figcaption></figure></section><section class="workbench landing-bench" aria-labelledby="bench-heading"><div class="section-label">Live workbench</div><h2 id="bench-heading">Record a quick comparison</h2>${workbench()}</section><section id="how" class="how" aria-labelledby="how-heading"><p class="eyebrow">How it works</p><h2 id="how-heading">Make one small change at a time</h2><ol><li><b>Record a baseline.</b><span>Say the same short line for up to 15 seconds.</span></li><li><b>Change one setup detail.</b><span>Move closer, lower gain, or quiet the room.</span></li><li><b>Compare the marks.</b><span>Keep the take that feels more comfortable.</span></li></ol></section><section class="boundaries" aria-labelledby="limits-heading"><h2 id="limits-heading">What these readings do not say</h2><p>They describe this recording setup. They do not judge your voice or assess hearing or health.</p></section>`, 'Compare two voice takes privately'); }
function wave(values: number[], label: string) { const bars = values.slice(0, 74).map((n, i) => `<i style="height:${Math.max(4, Math.round(n * 68))}px" aria-hidden="true"></i>`).join(''); return `<div class="wave" role="img" aria-label="${esc(label)} waveform"><span>${bars}</span></div>`; }
function status(t: Take) { const loud = t.loudness > .68 ? 'strong' : t.loudness < .28 ? 'soft' : 'steady'; const room = t.noise > .42 ? 'noticeable' : 'low'; return `<dl class="metrics"><div><dt>Level</dt><dd>${loud}</dd></div><div><dt>Room noise</dt><dd>${room}</dd></div><div><dt>Length</dt><dd>${t.duration.toFixed(1)}s</dd></div></dl>`; }
function takeCard(t: Take, index: number) { return `<article class="take-card"><div class="take-top"><span class="tag">TAKE ${index + 1}</span><button class="icon-btn" data-delete="${t.id}" aria-label="Delete ${esc(t.name)}">×</button></div><h3>${esc(t.name)}</h3>${wave(t.waveform, `${t.name} sound shape`)}${status(t)}<div class="take-actions"><button data-play="${t.id}">Play take</button><button data-wav="${t.id}">Export WAV</button></div></article>`; }
function workbench() { const next = takes.length < 2 ? takes.length + 1 : 2; return `<div class="bench-grid"><section class="record-panel" aria-labelledby="record-heading"><p class="section-label">Your turn</p><h2 id="record-heading">${takes.length ? 'Try a different setup' : 'Start with a short line'}</h2><p class="prompt">Say: “I can hear myself clearly in this room.”</p><label class="check"><input type="checkbox" id="distance" /> I changed my distance or room.</label><button class="record-btn" data-record ${takes.length >= 2 ? 'disabled' : ''}><span></span> Record take ${next} <small>up to 15 seconds</small></button><p class="record-status" aria-live="polite">${takes.length >= 2 ? 'Two takes are ready to compare.' : 'Your microphone is only requested when you record.'}</p>${takes.length ? `<button class="text-btn" data-clear>Delete all takes</button>` : ''}</section><section class="takes" aria-label="Your takes">${takes.length ? takes.map(takeCard).join('') : `<div class="empty"><b>Your takes will appear here.</b><span>Record a first take, then make one small change.</span></div>`}</section></div>${takes.length === 2 ? comparison() : ''}`; }
function comparison() { const [a,b] = takes; const closer = b.loudness > a.loudness + .1 ? 'Take 2 has a stronger level.' : a.loudness > b.loudness + .1 ? 'Take 1 has a stronger level.' : 'Both takes have a similar level.'; const quieter = b.noise < a.noise ? 'Take 2 has less room noise.' : b.noise > a.noise ? 'Take 1 has less room noise.' : 'Both takes have similar room noise.'; return `<section class="comparison" aria-labelledby="compare-heading"><p class="section-label">Comparison note</p><h2 id="compare-heading">Look for the setup you prefer</h2><p>${closer} ${quieter} Pick the one that feels easiest to hear.</p><button class="primary" data-keep="${a.noise <= b.noise ? a.id : b.id}">Keep the quieter take</button></section>`; }
function appPage() { return layout(`${demoBanner()}<section class="app-intro"><p class="eyebrow">Local recorder</p><h1>Record two short voice takes</h1><p>Compare simple level and room-noise marks before you keep one.</p></section><section class="workbench">${workbench()}</section><section class="guidance"><h2>Three setup prompts</h2><ul><li>Keep your mouth about a hand’s width from the microphone.</li><li>Record the same line for each take.</li><li>Change one thing before the second take.</li></ul></section>`, 'Record two short voice takes'); }
function infoPage(kind: 'privacy' | 'terms') { const privacy = kind === 'privacy'; const body = privacy ? `<h1>Your voice stays on your device</h1><p>Voice Comfort Meter stores recordings in this browser only. It does not upload audio or use analytics.</p><h2>What is stored</h2><p>Your recording files and the simple marks shown beside them stay in this browser. Delete a take or clear browser site data to remove them.</p><h2>Permissions</h2><p>The app asks for microphone permission only after you press Record. You can change that permission in your browser.</p>` : `<h1>Use this recording guide responsibly</h1><p>Voice Comfort Meter gives simple recording guidance. It does not assess voice quality, hearing, or health.</p><h2>Your recordings</h2><p>You control your recordings. Export or delete them whenever you want.</p><h2>No warranty</h2><p>This free tool is provided as-is. Check your equipment and recording environment before important work.</p>`; return layout(`<article class="legal">${body}</article>`, privacy ? 'Your voice stays on your device' : 'Use this recording guide responsibly'); }
function notFound() { return layout(`<section class="not-found"><p class="eyebrow">404 / LOST PAGE</p><h1>This sheet is not on the board</h1><p>Try the recorder or return to the home sheet.</p><a class="primary link-button" href="/" data-link>Go to the recorder</a></section>`, 'This sheet is not on the board'); }
async function render() { await load(); const r = route(); document.title = title(r); app.innerHTML = r === '/' ? landing() : r === '/demo' ? appPage() : r === '/privacy' || r === '/terms' ? infoPage(r.slice(1) as 'privacy'|'terms') : notFound(); document.querySelector('.route-note')!.textContent = document.querySelector('h1')!.textContent || ''; wire(); requestAnimationFrame(() => { document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true}); scrollTo(0, savedScroll.get(location.pathname) || 0); }); }
function sampleWav(freq: number) { const rate=16000, secs=3, samples=rate*secs, data=new Float32Array(samples); for(let i=0;i<samples;i++){ const gate=(Math.sin(i/(rate*.3))>.1?1:.25); data[i]=Math.sin(2*Math.PI*freq*i/rate)*(.14+(.22*Math.abs(Math.sin(i/450))))*gate; } return makeWav(data,rate); }
function makeWav(data: Float32Array, rate: number) { const b=new ArrayBuffer(44+data.length*2), v=new DataView(b); const text=(o:number,s:string)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0))); text(0,'RIFF');v.setUint32(4,36+data.length*2,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,data.length*2,true);data.forEach((x,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,x))*0x7fff,true));return new Blob([b],{type:'audio/wav'}); }
async function seedDemo() { takes=[{id:'sample-1',name:'Desk distance',blob:sampleWav(188),waveform:[.12,.25,.48,.35,.65,.42,.25,.7,.42,.58,.22,.44,.72,.31,.56,.2,.35,.63,.3,.48],loudness:.42,noise:.31,duration:3,created:Date.now()},{id:'sample-2',name:'One hand closer',blob:sampleWav(215),waveform:[.13,.4,.55,.62,.78,.46,.4,.8,.6,.73,.34,.54,.81,.44,.67,.32,.52,.76,.42,.66],loudness:.58,noise:.18,duration:3,created:Date.now()}];await save();render(); }
async function startRecord(button: HTMLButtonElement) { if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { statusText('Recording is not supported here. Try a current browser with microphone access.'); return; } try { stream=await navigator.mediaDevices.getUserMedia({audio:true}); audioCtx=new AudioContext(); const source=audioCtx.createMediaStreamSource(stream); analyser=audioCtx.createAnalyser(); analyser.fftSize=512; source.connect(analyser); const chunks:Blob[]=[]; recorder=new MediaRecorder(stream); const samples:number[]=[]; const tick=()=>{if(!recorder || recorder.state!=='recording'||!analyser)return;const d=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(d);let sum=0;d.forEach(x=>sum+=(x-128)**2);samples.push(Math.min(1,Math.sqrt(sum/d.length)/40));requestAnimationFrame(tick);}; recorder.ondataavailable=e=>chunks.push(e.data); recorder.onstop=async()=>{ const duration=Math.min(15,Math.max(.1,samples.length/60)); const mean=samples.reduce((a,b)=>a+b,0)/Math.max(1,samples.length); const noise=samples.slice(0,Math.min(20,samples.length)).reduce((a,b)=>a+b,0)/Math.max(1,Math.min(20,samples.length)); takes.push({id:crypto.randomUUID(),name:`Take ${takes.length+1}`,blob:new Blob(chunks,{type:recorder?.mimeType||'audio/webm'}),waveform:(samples.length?samples:[.1,.2,.3]).filter((_,i)=>i%Math.max(1,Math.floor(samples.length/62))===0),loudness:mean,noise,duration,created:Date.now()}); stream?.getTracks().forEach(t=>t.stop());audioCtx?.close();stream=null;recorder=null;clearTimeout(recordingTimer);await save();render();}; recorder.start(); button.classList.add('is-recording');button.innerHTML='<span></span> Stop recording <small>15 seconds maximum</small>';button.onclick=()=>recorder?.stop(); statusText('Recording now. Press Stop when you finish.'); requestAnimationFrame(tick); recordingTimer=window.setTimeout(()=>recorder?.stop(),15000); } catch(e) { const denied=(e as DOMException).name==='NotAllowedError'; statusText(denied?'Microphone access was blocked. Allow it in your browser, then press Record again.':'The microphone could not start. Check that another app is not using it, then try again.'); } }
function statusText(msg:string){const s=document.querySelector<HTMLElement>('.record-status');if(s)s.textContent=msg;}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),200);}
async function toWav(blob:Blob){if(blob.type==='audio/wav')return blob;const ac=new AudioContext();try{const buf=await ac.decodeAudioData(await blob.arrayBuffer());const mono=new Float32Array(buf.length);for(let c=0;c<buf.numberOfChannels;c++){const d=buf.getChannelData(c);d.forEach((v,i)=>mono[i]+=v/buf.numberOfChannels);}return makeWav(mono,buf.sampleRate);}finally{ac.close();}}
function wire() { document.querySelector<HTMLAnchorElement>('.skip')?.addEventListener('click',e=>{e.preventDefault();document.querySelector<HTMLElement>('#main')?.focus();}); document.querySelectorAll<HTMLAnchorElement>('[data-link]').forEach(a=>a.addEventListener('click',e=>{const h=a.getAttribute('href')!;if(h.startsWith('#'))return;e.preventDefault();navigate(h);})); document.querySelector('[data-demo]')?.addEventListener('click',()=>navigate('/demo')); document.querySelector('[data-real]')?.addEventListener('click',()=>navigate('/')); document.querySelector('[data-reset-demo]')?.addEventListener('click',seedDemo); document.querySelector<HTMLButtonElement>('[data-record]')?.addEventListener('click',e=>startRecord(e.currentTarget as HTMLButtonElement)); document.querySelector('[data-clear]')?.addEventListener('click',()=>{if(confirm('Delete both takes from this browser?'))clear();}); document.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{takes=takes.filter(t=>t.id!==b.dataset.delete);await save();render();}));document.querySelectorAll<HTMLButtonElement>('[data-play]').forEach(b=>b.addEventListener('click',()=>{const t=takes.find(x=>x.id===b.dataset.play);if(t){const a=new Audio(URL.createObjectURL(t.blob));a.play();}}));document.querySelectorAll<HTMLButtonElement>('[data-wav]').forEach(b=>b.addEventListener('click',async()=>{const t=takes.find(x=>x.id===b.dataset.wav);if(t){b.disabled=true;b.textContent='Preparing WAV…';try{download(await toWav(t.blob),`${t.name.toLowerCase().replaceAll(' ','-')}.wav`);}catch{statusText('This take could not be converted. Try recording it again.');}finally{b.disabled=false;b.textContent='Export WAV';}}}));document.querySelector('[data-keep]')?.addEventListener('click',()=>statusText('Preferred take marked. Export it or leave it stored here.')); }
window.addEventListener('popstate',render); window.addEventListener('online',()=>statusText('You are back online.')); window.addEventListener('offline',()=>statusText('Offline: your saved takes are still here.'));
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
if (demo()) seedDemo(); else render();
